import { NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server';

export async function POST(request: Request) {
  try {
    // Get authenticated user
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Get stock symbol from request body
    const body = await request.json();
    const { symbol } = body;
    
    if (!symbol) {
      return NextResponse.json({ error: "Stock symbol is required" }, { status: 400 });
    }

    // Call Flask backend to generate the report
    const response = await fetch(
      `${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000'}/generate-organization-financial-report`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
          symbol,
          user_id: userId,
          data_type: "organization"
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      console.error(`Backend error: ${errorText}`);
      return NextResponse.json(
        { error: `Failed to generate report: Server responded with ${response.status}` },
        { status: response.status }
      );
    }

    const data = await response.json();
    
    // Check if report was successfully generated by backend
    if (data.success && data.report_path) {
      const filename = data.report_path.split('/').pop();
      
      return NextResponse.json({
        success: true,
        filename,
        report_path: data.report_path,
        charts: data.charts || {},
        message: 'Stock report generated successfully'
      });
    } else {
      console.error('Backend did not return success or report_path');
      return NextResponse.json({
        success: false,
        error: 'Report generation failed on the server'
      }, { status: 500 });
    }
  } catch (error) {
    console.error('Report generation error:', error);
    return NextResponse.json(
      { error: 'Failed to generate report due to an unexpected error' },
      { status: 500 }
    );
  }
}